name: On Create Branch

# Trigger only on creation of a branch with the given pattern
on:
  push:
    types:
      - created
    branches:
      - releases/v*-rc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test trigger for being a release branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/release/"* ]]; then
            echo "${{ github.ref }} is a release branch";
            exit 0;
          else
            echo "${{ github.ref }} is not a release branch";
            exit 1;
          fi
